apiVersion: batch/v1
kind: Job
metadata:
  name: restore-backups
spec:
  backoffLimit: 1
  template:
    spec:
      securityContext:
        supplementalGroups: [1000]
      containers:
      - name: restore-backups
        image: ovenube/ovenube-worker:v12.0.2
        args: ["restore-backup"]
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: sites-dir
            mountPath: /home/frappe/frappe-bench/sites
        env:
          - name: "MYSQL_ROOT_PASSWORD"
            valueFrom:
              secretKeyRef:
                key: password
                name: mariadb-root-password
          - name: "BUCKET_NAME"
            value: ovenube-erpnext-backups
          - name: "ACCESS_KEY_ID"
            valueFrom:
              secretKeyRef:
                key: accessKey
                name: push-backup-s3-secret
          - name: "SECRET_ACCESS_KEY"
            valueFrom:
              secretKeyRef:
                key: secretKey
                name: push-backup-s3-secret
          - name: "ENDPOINT_URL"
            value: "https://s3.amazonaws.com"
          - name: "REGION"
            value: "us-east-1"
          - name: "BUCKET_DIR"
            value: backups
      restartPolicy: Never
      volumes:
        - name: sites-dir
          persistentVolumeClaim:
            claimName: frappe-bench-0001-erpnext
            readOnly: false